openapi: 3.0.3
info:
  title: Swagger Odds - OpenAPI 3.0
  description: ''
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://{url}/api/v1
paths:
  /odds:
    get:
      tags:
        - odds
      summary: Gets Head to Head Win odds for matches filtered by team(s) & competition(s)
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      parameters:
        - name: competitionIds
          description: Array of competition IDs
          in: query
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
        - name: notBefore
          description: Returns games where the kick off is after this value (UTC)
          in: query
          required: false
          schema:
            type: string
            format: date-time
            example: '2023-09-02T15:00:00Z'
        - name: notAfter
          description: Returns games where the kick off is before this value (UTC)
          in: query
          required: false
          schema:
            type: string
            format: date-time
            example: '2023-09-02T15:00:00Z'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '204':
          description: No matches found
        '400':
          description: Invalid status value
        '500':
          description: Internal server error
components:
  schemas:
    response:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/match'
      xml:
        name: Response
    match:
      type: object
      properties:
        matchId:
          type: string
          example: f397a59c-58d3-46b0-88d9-b461bb17e190
        matchName:
          type: string
          example: Western Sydney Wanderers vs Adelaide United FC
        competitionId:
          type: string
          example: 83208e3b-19db-4561-96b7-71e01b90f12f
        competitionName:
          type: string
          example: 'Australia: FFA Cup 2023'
        kickoffTime:
          type: string
          description: Kick off time (UTC)
          format: date-time
          example: '2023-09-02T15:00:00Z'
        odds:
          type: array
          items:
            $ref: '#/components/schemas/odds'
      xml:
        name: Match
    odds:
      type: object
      properties:
        teamName:
          type: string
          example: Western Sydney Wanderers
        url:
          type: string
          example: https://deeplink/to/odds
        return:
          type: number
          example: 4.56
      xml:
        name: Team
